app_name: harrymack
enviornment: !ENV ${ENVIORNMENT}
import_csv: ./HarryMackClips.csv
log_level: !ENV ${LOGLEVEL}
overwrite_destination: false
overwrite_download: false
env_dev:
  download_directory: ./media/downloads/
  music_root: ./media/musicroot/
env_prod:
  download_directory: /downloads/
  music_root: /music/
fonts:
  font_name: ./media/fonts/courbd.ttf
  font_sample: false
  init_font_size: 48
  max_font_size: 48
plex:
  baseurl: !ENV ${PLEXURL}
  token: !ENV ${PLEX}
